### PR TITLE
[WIP] Add JWT authentication

### PR DESCRIPTION
**Pull request by vgeorge**
Implements JWT authentication with [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2), mostly done. Remaining items:

- Look at the documentation for more robust/safe way of setting the JWT secret. Maybe creating a local.json after `npm install`?
- Return JWT at `/login` route on non-test enviroment, now it only returns it in simulated OAuth logins

### CODE REVIEW

**Comment by vgeorge** [comment]
@batpad I've added a env var JWT_SECRET and enforced that is should be set in production, otherwise the server won't start. 

Regarding the `/login` route, it now returns the user profile and a JWT token. You mentioned that it should redirect to a link in the app. Can you provide more details or an example on how this would work? I believe the behavior would be the same in the dashboard, maybe this endpoint should require a callback URL?

**Comment by batpad** [comment]
> I believe the behavior would be the same in the dashboard, maybe this endpoint should require a callback URL?

I believe allowing the client to specify a callback url will be best, yes. I am not sure if it would be best practice to implement a whitelist of allowed callback URL schemes / paths.

**Comment by batpad** [comment]
@vgeorge the login works well, and the code looks good to me.

I guess accepting a `callback_url` for the login route would be the next step? Your call whether you think it's better to do this in this PR or separately. Also not sure if we need to do any research on any best practices for the `callback_url` implementation.

**Comment by vgeorge** [comment]
Thanks for the review @batpad. I'm merging this, lets figure out the details for the final step at #2. I'll add some notes there.

**Pull request merged**
