### PR TITLE
Enable filters on traces/photos

### PR DESCRIPTION
**Pull request by vgeorge**
This enables passing query parameters to filter traces/photos.

### CODE REVIEW

**Comment by vgeorge** [comment]
@batpad this is ready for review. You can see filters working in the frontend by using code from PR https://github.com/developmentseed/observe-dashboard/pull/45.

**Comment by geohacker** [comment]
@vgeorge this is looking great! I ran into an issue with the date filters. This could also be a problem on the dashboard side. When I searched for traces between 25/07/2019 and 25/07/2019, it returned as expected. But when I search for 25/07/2019 and 27/07/2019, it returns no results. This is using the mock data -- running both the API and dashboard locally.

**Comment by vgeorge** [comment]
@geohacker I've made the endpoints accept `null` and `''` for descriptions and osmElements. Also updated the hapi setup to return detailed validation error messages in all routes. Can I merge?

**Comment by geohacker** [comment]
@vgeorge :shipit: looks good to merge. Thank you!

**Pull request merged**
